# Generated by Django 3.1.6 on 2021-03-17 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210312_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(related_name='subscribers', through='base.CategorySubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
