# Generated by Django 3.1.6 on 2021-03-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210312_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscriber',
        ),
    ]
